### ISSUE TITLE
Encoding warning and Error in `dplyr::mutate()`: when using create_translation_table

### ISSUE THREAD

**Issue by tjbrailey** [Tomeriko96/polyglotr#14] opened 2024-07-27 15:16 UTC
**Describe the bug**
When running the ```create_translation_table()``` function using the minimum working example provided in this packages' readme file, I get the following warning and error: 

```
No encoding supplied: defaulting to UTF-8.
Error in `dplyr::mutate()`:
ℹ In argument: `es = purrr::map_chr(original_word, ~google_translate(., target_language = language))`.
Caused by error in `purrr::map_chr()`:
ℹ In index: 1.
Caused by error:
! Result must be length 1, not 0.
Run `rlang::last_trace()` to see where the error occurred.
```

I'm not sure if this is an issue with my machine, but the error message itself doesn't really give me any clues as to the issue (though perhaps it is related to the encoding warning provided before the error message?).

**To Reproduce**
```
> library(polyglotr)
> texts <- c("Hello, how are you?", 
+            "I love programming!", 
+            "This is a test.")
> 
> languages <- c("es", 
+                "fr", 
+                "de")
> 
> 
> create_translation_table(texts, languages)
```

**Session info**
```
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] polyglotr_1.5.1

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5       httr_1.4.7        cli_3.6.3         rlang_1.1.4       stringi_1.8.4     processx_3.8.4    purrr_1.0.2       promises_1.3.0    generics_0.1.3   
[10] jsonlite_1.8.8    glue_1.7.0        selectr_0.4-2     ps_1.7.7          triebeard_0.4.1   chromote_0.2.0    fansi_1.0.6       tibble_3.2.1      fastmap_1.2.0    
[19] lifecycle_1.0.4   stringr_1.5.1     compiler_4.3.2    rvest_1.0.4       dplyr_1.1.4       websocket_1.4.2   Rcpp_1.0.13       pkgconfig_2.0.3   rstudioapi_0.16.0
[28] later_1.3.2       R6_2.5.1          tidyselect_1.2.1  utf8_1.2.4        pillar_1.9.0      curl_5.2.1        magrittr_2.0.3    urltools_1.7.3    tools_4.3.2      
[37] xml2_1.3.6   
```

Thanks in advance for your help!

**Comment by Tomeriko96** [comment] 2024-07-28 10:48
Hi @tjbrailey ,

I am afraid I cannot reproduce your issue:

``` r
install.packages("polyglotr")
#> Installing package into '/usr/local/lib/R/site-library'
#> (as 'lib' is unspecified)
```

``` r
library(polyglotr)
texts <- c("Hello, how are you?",
           "I love programming!", 
           "This is a test.")
languages <- c("es", "fr", "de")

create_translation_table(texts, languages)
#>         original_word                     es                          fr
#> 1 Hello, how are you?     ¿Hola, cómo estás? Bonjour comment allez-vous?
#> 2 I love programming! ¡Me encanta programar!  J'adore la programmation !
#> 3     This is a test.    Esto es una prueba.              C'est un test.
#>                         de
#> 1  Hallo, wie geht es dir?
#> 2 Ich liebe Programmieren!
#> 3        Das ist ein Test.
```

<sup>Created on 2024-07-28 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.4.1 (2024-06-14)
#>  os       Ubuntu 22.04.4 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Etc/UTC
#>  date     2024-07-28
#>  pandoc   3.2 @ /usr/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.2   2023-12-11 [1] RSPM (R 4.4.0)
#>  curl          5.2.1   2024-03-01 [1] RSPM (R 4.4.0)
#>  digest        0.6.35  2024-03-11 [1] RSPM (R 4.4.0)
#>  dplyr         1.1.4   2023-11-17 [1] RSPM (R 4.4.0)
#>  evaluate      0.24.0  2024-06-10 [1] RSPM (R 4.4.0)
#>  fansi         1.0.6   2023-12-08 [1] RSPM (R 4.4.0)
#>  fastmap       1.2.0   2024-05-15 [1] RSPM (R 4.4.0)
#>  fs            1.6.4   2024-04-25 [1] RSPM (R 4.4.0)
#>  generics      0.1.3   2022-07-05 [1] RSPM (R 4.4.0)
#>  glue          1.7.0   2024-01-09 [1] RSPM (R 4.4.0)
#>  htmltools     0.5.8.1 2024-04-04 [1] RSPM (R 4.4.0)
#>  httr          1.4.7   2023-08-15 [1] RSPM (R 4.4.0)
#>  knitr         1.47    2024-05-29 [1] RSPM (R 4.4.0)
#>  lifecycle     1.0.4   2023-11-07 [1] RSPM (R 4.4.0)
#>  magrittr      2.0.3   2022-03-30 [1] RSPM (R 4.4.0)
#>  pillar        1.9.0   2023-03-22 [1] RSPM (R 4.4.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] RSPM (R 4.4.0)
#>  polyglotr   * 1.5.1   2024-07-27 [1] RSPM (R 4.4.1)
#>  purrr         1.0.2   2023-08-10 [1] RSPM (R 4.4.0)
#>  R.cache       0.16.0  2022-07-21 [1] RSPM (R 4.4.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] RSPM (R 4.4.0)
#>  R.oo          1.26.0  2024-01-24 [1] RSPM (R 4.4.0)
#>  R.utils       2.12.3  2023-11-18 [1] RSPM (R 4.4.0)
#>  R6            2.5.1   2021-08-19 [1] RSPM (R 4.4.0)
#>  Rcpp          1.0.12  2024-01-09 [1] RSPM (R 4.4.0)
#>  reprex        2.1.0   2024-01-11 [1] RSPM (R 4.4.0)
#>  rlang         1.1.4   2024-06-04 [1] RSPM (R 4.4.0)
#>  rmarkdown     2.27    2024-05-17 [1] RSPM (R 4.4.0)
#>  rstudioapi    0.16.0  2024-03-24 [1] RSPM (R 4.4.0)
#>  rvest         1.0.4   2024-02-12 [1] RSPM (R 4.4.0)
#>  selectr       0.4-2   2019-11-20 [1] RSPM (R 4.4.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.4.0)
#>  stringi       1.8.4   2024-05-06 [1] RSPM (R 4.4.0)
#>  stringr       1.5.1   2023-11-14 [1] RSPM (R 4.4.0)
#>  styler        1.10.3  2024-04-07 [1] RSPM (R 4.4.0)
#>  tibble        3.2.1   2023-03-20 [1] RSPM (R 4.4.0)
#>  tidyselect    1.2.1   2024-03-11 [1] RSPM (R 4.4.0)
#>  triebeard     0.4.1   2023-03-04 [1] RSPM (R 4.4.0)
#>  urltools      1.7.3   2019-04-14 [1] RSPM (R 4.4.0)
#>  utf8          1.2.4   2023-10-22 [1] RSPM (R 4.4.0)
#>  vctrs         0.6.5   2023-12-01 [1] RSPM (R 4.4.0)
#>  withr         3.0.0   2024-01-16 [1] RSPM (R 4.4.0)
#>  xfun          0.44    2024-05-15 [1] RSPM (R 4.4.0)
#>  xml2          1.3.6   2023-12-04 [1] RSPM (R 4.4.0)
#>  yaml          2.3.8   2023-12-11 [1] RSPM (R 4.4.0)
#> 
#>  [1] /usr/local/lib/R/site-library
#>  [2] /usr/local/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by Tomeriko96** [comment] 2024-07-28 10:49
Could you provide me the output of "Run `rlang::last_trace()` to see where the error occurred."?

**Comment by tjbrailey** [comment] 2024-07-28 16:34
Hi there, here is the output from ```rlang::last_trace()```

```
<error/dplyr:::mutate_error>
Error in `dplyr::mutate()`:
ℹ In argument: `es = purrr::map_chr(original_word, ~google_translate(., target_language = language))`.
Caused by error in `purrr::map_chr()`:
ℹ In index: 1.
Caused by error:
! Result must be length 1, not 0.
---
Backtrace:
     ▆
  1. ├─polyglotr::create_translation_table(texts, languages)
  2. │ └─translations %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(...)
  5. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  8. │     └─mask$eval_all_mutate(quo)
  9. │       └─dplyr (local) eval()
 10. └─purrr::map_chr(original_word, ~google_translate(., target_language = language))
 11.   └─purrr:::map_("character", .x, .f, ..., .progress = .progress)
 12.     ├─purrr:::with_indexed_errors(...)
 13.     │ └─base::withCallingHandlers(...)
 14.     └─purrr:::call_with_cleanup(...)
```

**Comment by Tomeriko96** [comment] 2024-07-31 06:44
Hi @tjbrailey ,

I am not sure, but it seems like the underlying functions does not provide you an output.

Can you confirm that the the underlying function `google_translate()` works and results in output?

**Comment by tjbrailey** [comment] 2024-07-31 16:08
If I run just the `google_translate` function on one of the sentences, translating just to French as an example, I get the following warning, and an empty output. Is it perhaps because I have reached a usage limit or something like that?
```polyglotr::google_translate(texts[1], target_language = "fr")```

```
No encoding supplied: defaulting to UTF-8.
character(0)
```

**Comment by Tomeriko96** [comment] 2024-08-02 11:23
Hi @tjbrailey ,

Hhmm. If you are still up to it, I would like to test some things to get a clear picture what the issue truly entails:

When running a part of the function and extracting the formatted link, I receive as value 


` [1] "https://translate.google.com/m?tl=fr&sl=auto&q=Hello%2c%20how%20are%20you%3f"`

1. Could you open this link in the browser and see if you are greeted with a translation?
2. Can you run the below script, and check if the value of `formatted_link` is the same as the link above?

You should see an object called `formatted_link` in your global environment.

```
google_translate <- function(text, target_language = "en", source_language = "auto") {

  if (!google_is_valid_language_code(target_language)) {
    stop("Invalid target language code.")
  }

  if (!google_is_valid_language_code(source_language)) {
    stop("Invalid source language code.")
  }

  is_vector <- is.vector(text) && length(text) > 1

  formatted_text <- urltools::url_encode(text)

  formatted_link <<- paste0(
    "https://translate.google.com/m?tl=",
    target_language, "&sl=", source_language,
    "&q=",
    formatted_text
  )

  if (is_vector) {
    responses <- purrr::map(formatted_link, httr::GET)

    translations <- purrr::map(responses, ~ {
      translation <- httr::content(.x) %>%
        rvest::html_nodes("div.result-container") %>%
        rvest::html_text()

      translation <- urltools::url_decode(translation)
      translation <- gsub("\n", "", translation)

      translation
    })

    return(translations)
  } else {
    response <- httr::GET(formatted_link)

    translation <- httr::content(response) %>%
      rvest::html_nodes("div.result-container") %>%
      rvest::html_text()

    translation <- urltools::url_decode(translation)
    translation <- gsub("\n", "", translation)

    return(translation)
  }
}

texts <- c("Hello, how are you?",
           "I love programming!", 
           "This is a test.")

google_translate(texts[1], target_language = "fr")

formatted_link

```

**Comment by tjbrailey** [comment] 2024-08-02 21:29
Yes definitely!

1. Yes, that link provides a translation in my browser.
2. Yes, `formatted_link` looks the same when I run the above code.

I ran each line in the function individually, and it looks like the error is (sometimes) coming from: 

```
response <- httr::GET(formatted_link)

translation <- httr::content(response) %>%
      rvest::html_nodes("div.result-container") %>%
      rvest::html_text()
```

Though I'm not 100% why that is (something to do with "div.result-container" not being found in the `response` object).

I can get the function to run (and not produce any error message/encoding warning) if I swap out the above lines with: 

```
 translation <- rvest::read_html(formatted_link) %>%
      rvest::html_nodes("div.result-container") %>%
      rvest::html_text()
```

**Comment by Tomeriko96** [comment] 2024-08-05 06:40
Nice catch!

Very interesting to read the latter code chunk works in your case.

I will run some tests this week to see if I can swap the current method with your implementation!

**Comment by Tomeriko96** [comment] 2024-08-05 06:58
Running some quick tests seem to work as intended.

You can use the function from the development version of the package for now. The fix has been implemented in commit 64223af9.

**Comment by tjbrailey** [comment] 2024-08-05 08:59
Awesome, thank you so much for doing this!

**Comment by Tomeriko96** [comment] 2024-08-13 18:04
Hi @tjbrailey,

Glad to read you find the package useful!

I normally keep issues open until the changes are available on CRAN. I will close it, when it has been updated there!

**Comment by tin900** [comment] 2024-08-19 07:37
The new version of `polyglotr` has been submitted to CRAN

**Closed by tin900** 2024-08-19 07:37 UTC
